language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run -m unittest discover unit_tests/ -v
  - coverage html
  - coverage xml -i
  - ./unit_tests/send_coverage_codacy.sh
  - sphinx-apidoc -f -o docs/source ./framework/models/
  - cd ./docs && make html