# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athlete.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='athlete.proto',
  package='query',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rathlete.proto\x12\x05query\"\xd6\x03\n\x07\x41thlete\x1a@\n\x04User\x12\x11\n\tuser_name\x18\x01 \x02(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x1aH\n\x05\x42ikes\x12,\n\nbike_brand\x18\x01 \x02(\x0e\x32\x18.query.Athlete.BikeBrand\x12\x11\n\tbike_name\x18\x02 \x01(\t\x1aH\n\x05Shoes\x12,\n\nshoe_brand\x18\x01 \x02(\x0e\x32\x18.query.Athlete.ShoeBrand\x12\x11\n\tshoe_name\x18\x02 \x01(\t\x1a\x9d\x01\n\x05Query\x12\n\n\x02id\x18\x01 \x02(\r\x12!\n\x04user\x18\x02 \x02(\x0b\x32\x13.query.Athlete.User\x12#\n\x05\x62ikes\x18\x03 \x03(\x0b\x32\x14.query.Athlete.Bikes\x12#\n\x05shoes\x18\x04 \x03(\x0b\x32\x14.query.Athlete.Shoes\x12\x0e\n\x06weight\x18\x05 \x01(\r\x12\x0b\n\x03\x61ge\x18\x06 \x01(\r\"2\n\tBikeBrand\x12\x0b\n\x07\x41VENTON\x10\x01\x12\n\n\x06\x43INELI\x10\x02\x12\x0c\n\x08\x45IGHTBAR\x10\x03\"!\n\tShoeBrand\x12\x08\n\x04NIKE\x10\x01\x12\n\n\x06\x41\x44IDAS\x10\x02'
)



_ATHLETE_BIKEBRAND = _descriptor.EnumDescriptor(
  name='BikeBrand',
  full_name='query.Athlete.BikeBrand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AVENTON', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CINELI', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EIGHTBAR', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=410,
  serialized_end=460,
)
_sym_db.RegisterEnumDescriptor(_ATHLETE_BIKEBRAND)

_ATHLETE_SHOEBRAND = _descriptor.EnumDescriptor(
  name='ShoeBrand',
  full_name='query.Athlete.ShoeBrand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NIKE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADIDAS', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=462,
  serialized_end=495,
)
_sym_db.RegisterEnumDescriptor(_ATHLETE_SHOEBRAND)


_ATHLETE_USER = _descriptor.Descriptor(
  name='User',
  full_name='query.Athlete.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='query.Athlete.User.user_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='query.Athlete.User.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='query.Athlete.User.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=100,
)

_ATHLETE_BIKES = _descriptor.Descriptor(
  name='Bikes',
  full_name='query.Athlete.Bikes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bike_brand', full_name='query.Athlete.Bikes.bike_brand', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bike_name', full_name='query.Athlete.Bikes.bike_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=174,
)

_ATHLETE_SHOES = _descriptor.Descriptor(
  name='Shoes',
  full_name='query.Athlete.Shoes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shoe_brand', full_name='query.Athlete.Shoes.shoe_brand', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shoe_name', full_name='query.Athlete.Shoes.shoe_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=248,
)

_ATHLETE_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='query.Athlete.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='query.Athlete.Query.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='query.Athlete.Query.user', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bikes', full_name='query.Athlete.Query.bikes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shoes', full_name='query.Athlete.Query.shoes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='query.Athlete.Query.weight', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='query.Athlete.Query.age', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=408,
)

_ATHLETE = _descriptor.Descriptor(
  name='Athlete',
  full_name='query.Athlete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ATHLETE_USER, _ATHLETE_BIKES, _ATHLETE_SHOES, _ATHLETE_QUERY, ],
  enum_types=[
    _ATHLETE_BIKEBRAND,
    _ATHLETE_SHOEBRAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=495,
)

_ATHLETE_USER.containing_type = _ATHLETE
_ATHLETE_BIKES.fields_by_name['bike_brand'].enum_type = _ATHLETE_BIKEBRAND
_ATHLETE_BIKES.containing_type = _ATHLETE
_ATHLETE_SHOES.fields_by_name['shoe_brand'].enum_type = _ATHLETE_SHOEBRAND
_ATHLETE_SHOES.containing_type = _ATHLETE
_ATHLETE_QUERY.fields_by_name['user'].message_type = _ATHLETE_USER
_ATHLETE_QUERY.fields_by_name['bikes'].message_type = _ATHLETE_BIKES
_ATHLETE_QUERY.fields_by_name['shoes'].message_type = _ATHLETE_SHOES
_ATHLETE_QUERY.containing_type = _ATHLETE
_ATHLETE_BIKEBRAND.containing_type = _ATHLETE
_ATHLETE_SHOEBRAND.containing_type = _ATHLETE
DESCRIPTOR.message_types_by_name['Athlete'] = _ATHLETE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Athlete = _reflection.GeneratedProtocolMessageType('Athlete', (_message.Message,), {

  'User' : _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
    'DESCRIPTOR' : _ATHLETE_USER,
    '__module__' : 'athlete_pb2'
    # @@protoc_insertion_point(class_scope:query.Athlete.User)
    })
  ,

  'Bikes' : _reflection.GeneratedProtocolMessageType('Bikes', (_message.Message,), {
    'DESCRIPTOR' : _ATHLETE_BIKES,
    '__module__' : 'athlete_pb2'
    # @@protoc_insertion_point(class_scope:query.Athlete.Bikes)
    })
  ,

  'Shoes' : _reflection.GeneratedProtocolMessageType('Shoes', (_message.Message,), {
    'DESCRIPTOR' : _ATHLETE_SHOES,
    '__module__' : 'athlete_pb2'
    # @@protoc_insertion_point(class_scope:query.Athlete.Shoes)
    })
  ,

  'Query' : _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
    'DESCRIPTOR' : _ATHLETE_QUERY,
    '__module__' : 'athlete_pb2'
    # @@protoc_insertion_point(class_scope:query.Athlete.Query)
    })
  ,
  'DESCRIPTOR' : _ATHLETE,
  '__module__' : 'athlete_pb2'
  # @@protoc_insertion_point(class_scope:query.Athlete)
  })
_sym_db.RegisterMessage(Athlete)
_sym_db.RegisterMessage(Athlete.User)
_sym_db.RegisterMessage(Athlete.Bikes)
_sym_db.RegisterMessage(Athlete.Shoes)
_sym_db.RegisterMessage(Athlete.Query)


# @@protoc_insertion_point(module_scope)
