# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import framework.models.pb2.example_v2.bike_pb2 as bike__pb2
import framework.models.pb2.example_v2.swim_pb2 as swim__pb2
import framework.models.pb2.example_v2.run_pb2 as run__pb2
import framework.models.pb2.example_v2.ski_pb2 as ski__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='query.proto',
  package='query',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bquery.proto\x12\x05query\x1a\nbike.proto\x1a\nswim.proto\x1a\trun.proto\x1a\tski.proto\"\xb6\x03\n\x07Request\x12\'\n\x06status\x18\x01 \x02(\x0e\x32\x17.query.Request.Activity\x12\'\n\x07private\x18\x02 \x02(\x0e\x32\x16.query.Request.Private\x12\n\n\x02id\x18\x03 \x02(\x05\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x04 \x02(\x0c\x12\x38\n\x10query_activities\x18\x05 \x02(\x0b\x32\x1e.query.Request.QueryActivities\x12\x0c\n\x04\x64\x61te\x18\x06 \x02(\x05\x1a\xa9\x01\n\x0fQueryActivities\x12%\n\nbike_query\x18\x01 \x03(\x0b\x32\x11.query.Bike.Query\x12%\n\nswim_query\x18\x02 \x03(\x0b\x32\x11.query.Swim.Query\x12#\n\trun_query\x18\x03 \x03(\x0b\x32\x10.query.Run.Query\x12#\n\tski_query\x18\x04 \x03(\x0b\x32\x10.query.Ski.Query\"#\n\x08\x41\x63tivity\x12\x0b\n\x07\x41RCHIVE\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\"\x1e\n\x07Private\x12\x08\n\x04TRUE\x10\x0f\x12\t\n\x05\x46\x41LSE\x10\x16\"\n\n\x08Response'
  ,
  dependencies=[bike__pb2.DESCRIPTOR,swim__pb2.DESCRIPTOR,run__pb2.DESCRIPTOR,ski__pb2.DESCRIPTOR,])



_REQUEST_ACTIVITY = _descriptor.EnumDescriptor(
  name='Activity',
  full_name='query.Request.Activity',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARCHIVE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=440,
  serialized_end=475,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_ACTIVITY)

_REQUEST_PRIVATE = _descriptor.EnumDescriptor(
  name='Private',
  full_name='query.Request.Private',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRUE', index=0, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FALSE', index=1, number=22,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=477,
  serialized_end=507,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_PRIVATE)


_REQUEST_QUERYACTIVITIES = _descriptor.Descriptor(
  name='QueryActivities',
  full_name='query.Request.QueryActivities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bike_query', full_name='query.Request.QueryActivities.bike_query', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swim_query', full_name='query.Request.QueryActivities.swim_query', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='run_query', full_name='query.Request.QueryActivities.run_query', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ski_query', full_name='query.Request.QueryActivities.ski_query', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=438,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='query.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='query.Request.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='private', full_name='query.Request.private', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='query.Request.id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_token', full_name='query.Request.access_token', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_activities', full_name='query.Request.query_activities', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='query.Request.date', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_QUERYACTIVITIES, ],
  enum_types=[
    _REQUEST_ACTIVITY,
    _REQUEST_PRIVATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=507,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='query.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=519,
)

_REQUEST_QUERYACTIVITIES.fields_by_name['bike_query'].message_type = bike__pb2._BIKE_QUERY
_REQUEST_QUERYACTIVITIES.fields_by_name['swim_query'].message_type = swim__pb2._SWIM_QUERY
_REQUEST_QUERYACTIVITIES.fields_by_name['run_query'].message_type = run__pb2._RUN_QUERY
_REQUEST_QUERYACTIVITIES.fields_by_name['ski_query'].message_type = ski__pb2._SKI_QUERY
_REQUEST_QUERYACTIVITIES.containing_type = _REQUEST
_REQUEST.fields_by_name['status'].enum_type = _REQUEST_ACTIVITY
_REQUEST.fields_by_name['private'].enum_type = _REQUEST_PRIVATE
_REQUEST.fields_by_name['query_activities'].message_type = _REQUEST_QUERYACTIVITIES
_REQUEST_ACTIVITY.containing_type = _REQUEST
_REQUEST_PRIVATE.containing_type = _REQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'QueryActivities' : _reflection.GeneratedProtocolMessageType('QueryActivities', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_QUERYACTIVITIES,
    '__module__' : 'query_pb2'
    # @@protoc_insertion_point(class_scope:query.Request.QueryActivities)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:query.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.QueryActivities)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:query.Response)
  })
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
